## About the Capital Improvement Program

### Capital budget

The City Charter requires that the Baltimore City Planning Commission recommend a six-year [Capital Improvement Program](https://planning.baltimorecity.gov/planning-capital-improvement) (CIP) to the [Board of Estimates](https://comptroller.baltimorecity.gov/boe) each year. The first year of this plan is included as the capital portion of the Baltimore City budget, adopted by the Baltimore City Council in June of each year in a bill known as the [Ordinance of Estimates](https://comptroller.baltimorecity.gov/boe/ooe).

The Baltimore City budget includes both the Operating Budget Plan and first year of the Capital Improvement Plan (also known as the Capital Budget). The operating budget funds the daily business of the City, specifically covering programs, services, staff, and supplies. The capital budget funds major renovations, upgrades, or replacements of physical infrastructure and assets. Budget publications available through [the Bureau of the Budget and Management Research website](https://bbmr.baltimorecity.gov/budget-publications).

The process of preparing the capital budget starts in the fall before the budget is adopted when Department of Planning staff start working with agency staff to update the six-year capital program. In January, each agency presents their proposed capital projects and program to the Planning Commission. The Planning Commission reviews the proposals and makes a recommendation to the Board of Estimates for which projects to include in six-year Capital Improvement Program. The recommended program must fit within the funding levels set forth by the Department of Finance.

### Review and adoption timeline

The Planning Commission recommends a new six-year Capital Improvement Program (CIP) each year.

-   Starting in late September, the Department of Planning works with participating city agencies to solicit project requests, prioritize projects for funding, and prepare the six-year plan.

-   Between December and February, Department staff collect CIP requests and performs a detailed review and prepares a public report.

-   In January, city agencies present CIP priorities to Planning Commission followed by the Planning Commission review and approval of the CIP by March.

{{< pagebreak >}}

### Participating agencies

Both Baltimore City agencies and quasi-public agencies participate in the capital budget process and prepare a six-year capital program each year.

Participating entities include:

-   Baltimore City Information Technology
-   Baltimore City Mayor’s Office
-   Baltimore City Public School System
-   Baltimore Convention Center
-   Baltimore Development Corporation
-   Department of General Services
-   Department of Housing and Community Development
-   Department of Public Works
-   Department of Recreation and Parks
-   Department of Transportation
-   Enoch Pratt Free Library
-   Parking Authority of Baltimore City

Agencies fund, plan and complete capital projects in different ways based on the agency structure and the needs of the agency’s specific projects. For example, the Department of General Services (DGS) manages buildings used by other city agencies including the Baltimore City Fire Department, Baltimore City Police Department, and Baltimore City Health Department. The Department of General Services also makes requests and identifies priorities on behalf of the Convention Center and the Enoch Pratt Free Library.

Notably, that the Baltimore City Public School System (BCPSS) Capital Improvement Program is approved separately from that of other agencies. The largest share of funds for the school system’s capital budget come from the State, through the State Public School Construction Program (PSCP) supported by the [Interagency Commission on School Construction](https://iac.mdschoolconstruction.org/) (IAC). The Planning Commission reviews the school system’s six-year program and request to the PSCP in the fall of each year. Baltimore City’s Capital Improvement Plan only includes City’s funds contributed to the school system’s regular capital budget so only projects supported by this funding are included in this report.

### Capital funding sources

Funding for capital improvements comes from a variety of sources, including general fund-backed sources, state and local funds, utility-related sources, and more.

General Funds (Pay-as-you-go)

:   Revenue received from various payments to the City, such as property taxes and sale of property. General Funds are mostly used for the operating budget, but Finance allocates a certain amount for PAYGO capital each year.

Highway User Revenue (HUR)

:   Formerly known as Motor Vehicle Revenue (MVR), funds are State Highway User Revenues allocated by formula. These state funds are restricted to eligible uses, such as transportation projects.

General Obligation Bonds (GO Bonds)

:   With voter approval, the City borrows money for specific improvements by selling general obligation bonds. GO bonds are debt secured by the full faith and credit of the City, and are presented to voters for approval every two years through questions on the general election ballot. This is a flexible fund source that allows the City to maintain some of its highest priority capital assets and programs, particularly those that are not eligible for any other fund source.

::: {.callout-note logo="false" title="General Obligation Bonds in FY25-30 CIP" appearance="simple"}
For the FY24 and FY25 capital budgets, voters approved \$160 million in General Obligation (GO) bonds across four specific loans: the 4th Affordable Housing loan (\$14 million), the 50th School loan (\$38 million), the 5th Community and Economic Development loan (\$36 million), and 2nd Public Infrastructure loan (\$72 million). The loans are for two years, so each year half of the amount is budgeted.
:::

State Funds

:   Funds from the State are typically in the form of grants, including grants made through Program Open Space.

Federal Funds

:   Federal loans and grants include Community Development Block Grants (CDBG), Federal Highway Administration (FHWA) grants, and other sources.

Revenue Bonds

:   Bonds issued by city agencies to be repaid with future dedicated revenue, such as water, wastewater, and stormwater revenue collected from water bills by the Department of Public Works. At times, revenue bonds can be used for non-utility related projects (if an appropriate revenue source is identified and approved by the Department of Finance).

::: {.callout-note logo="false" title="Revenue Bonds in FY25-30 CIP" appearance="simple"}
The Department of Finance authorized the Parking Authority of Baltimore City to budget Parking Revenue bonds as a source for FY25 to FY29 budgets. Parking revenue bonds are loans for improvements that are paid back by future revenues from parking fees and fines.
:::

Utility Funds

:   Utility funds include current operating revenues from City utilities such as water bills and conduit fees.

Other

:   Other possible sources include County grants, Local Impact Aid, private monies, and more.

### Evaluation criteria

Planning staff work with agency staff to determine priority projects for each agency. In making their recommendations, staff consider alignment with agency priorities, evaluation criteria and scores, what additional funding may be needed to bid projects or continue to assemble funds for construction, programmatic items at the level prioritized by the agency, constraints of the fund source, and potential for alternative sources of funding.

In recent years, Department staff worked with focus groups to update the evaluation criteria used in this process. In addition to providing helpful information for the decision-making process, the criteria can act as a guide to what is most important in a capital project, to help agencies develop the most impactful projects. The evaluation criteria are detailed in the table below.

|                     Criteria | Key questions                                                                                       |
|--------------------------:|---------------------------------------------|
|                      Mandate | Is this required by Federal, State, or local law?                                                   |
|                       Equity | Does this address a gap in outcomes based on race, religion, gender, sexual orientation, or income? |
|            Health and Safety | Is there an immediate or long-term health or safety benefit?                                        |
|              Asset Condition | What is the condition of the building or asset?                                                     |
|         Return on Investment | Will this increase tax revenue, reduce costs to the City, or leverage other funds?                  |
|         Environmental Impact | Will the project improve air or water quality or reduce greenhouse gas emissions?                   |
| Efficiency and Effectiveness | Is the project an efficient and effective solution to a problem the agency is trying to solve?      |

