---
title: "Baltimore City FY25-30 Capital Improvement Program"
author: "Baltimore City Department of Planning"
output-file: "FY2530_CIP-BOE-Recommendation-Report.pdf"
date: last-modified
papersize: letter
execute: 
  error: true
  eval: false
params:
  cip_type: "recommendation"
  stage: "BOE"
  title_short: "FY25-30 CIP Report"
---

```{r}
library(targets)
library(here)
# store_path <- here(targets::tar_config_get("store"))
# store_path <- targets::tar_config_get("store")

# tar_option_set(
#   store = here(tar_config_get("store"))
# )

# FIXME: Check if all of the following are required or if any can be dropped
report_xwalks <- tar_read(report_xwalks)

cip_project_details <- tar_read(cip_project_details)

cip_pc_comparison_summary <- tar_read(cip_pc_comparison_summary)

asset_list <- tar_read(asset_list)

agency_reference <- tar_read(agency_reference)

report_data <- tar_read(cip_report_data)

# cip_location_plots <- tar_read(cip_location_plots)
```

```{r}
suppressPackageStartupMessages(
  suppressWarnings(
    targets::tar_source(
      files = here::here("R")
    )
  )
)

options(
  fy_cols = paste0("fy", 2026:2030),
  tbl_fy_cols = c(paste0("fy_", c(2025:2030)), "fy_total"),
  tbl_fy_labels = c(paste0("FY", c(25:30)), "Total ($K)")
)

cip_term <- switch(params$stage,
  "Agency" = "request",
  "recommendation"
)

cip_verb <- switch(cip_term,
  "request" = "requested",
  "recommendation" = "recommended"
)

cip_singular <- cip_term
cip_plural <- paste0(cip_term, "s")
cip_singular_title <- str_to_title(cip_singular)
cip_plural_title <- str_to_title(cip_plural)
cip_data_col <- paste0(cip_singular, "_data")

report_org_name <- switch(params$stage,
  "Agency" = "Agencies",
  "PC" = "Planning Commission",
  "BOF" = "Board of Finance",
  "BOE" = "Board of Estimates",
  "CC" = "Council"
)

report_org_name_long <- paste0(
  "Baltimore City ",
  report_org_name
)

report_org_abb <- switch(params$stage,
  "Agency" = "Agencies",
  "PC" = "PC",
  "BOF" = "BOF",
  "BOE" = "BOE",
  "CC" = "CC"
)

recommendation_date <- "April 2024"

stage_filename <- switch(params$stage,
  "Agency" = "Capital_Projects_-_Six-Year_CIP_Requests.xlsx",
  "PC" = "Capital_Projects_-_Six-Year_CIP_PC-Recommendations.xlsx",
  "BOF" = "Capital_Projects_-_Six-Year_CIP_BOF-Recommendations.xlsx",
  "BOE" = "Capital_Projects_-_Six-Year_CIP_BOE-Recommendations.xlsx",
  "CC" = "Capital_Projects_-_Six-Year_CIP_CC-Capital-Budget.xlsx"
)

cip_recommendations <- switch(params$stage,
  # "Agency" = "Capital_Projects_-_Six-Year_CIP_Requests.xlsx",
  "PC" = tar_read(cip_pc_recommendations),
  "BOF" = tar_read(cip_bof_recommendations),
  "BOE" = tar_read(cip_boe_recommendations) # ,
  # "CC" = "Capital_Projects_-_Six-Year_CIP_CC-Capital-Budget.xlsx"
)
```

```{r}
#| eval: false
sample_n <- 500
report_data <- report_data |>
  slice_sample(n = sample_n)
```

{{< pagebreak >}}

# Introduction

{{< include report/_intro_summary.qmd >}}

{{< include report/_intro_about-cip.qmd >}}

{{< include report/_intro_about-cip-report.qmd >}}

{{< pagebreak >}}

# Capital Project `r cip_plural_title` by Agency

```{r}
#| output: asis
report_data |>
  nest_by(agency_label, .keep = TRUE) |>
  # Create and show each agency report
  knit_children(
    agency_label,
    data,
    .input = here("report", "children", "_agency_report.qmd"),
    .params = list2(
      agency_reference = agency_reference,
      agency_level = 2,
      internal_report = FALSE # ,
      # cip_location_plots = cip_location_plots
    )
  )
```

# Appendices

<!-- {{< include report/_appendix_recommendations.qmd >}} -->

{{< include report/_appendix_project-identifier.qmd >}}

{{< include report/_appendix_report-creation.qmd >}}

{{< include report/_appendix_updates.qmd >}}

