---
title: "Baltimore City FY25-30 Capital Improvement Program"
author: "Baltimore City Department of Planning"
date: last-modified
papersize: letter
format:
  dopPDF-pdf:
    toc-depth: 2
    keep-tex: true
params:
  cip_type: "recommendation"
  stage: "Ordinance"
  title_short: "FY25-30 CIP Report"
---

```{r}
targets::tar_source(
  files = here::here("R")
)

options(
  fy_cols = paste0("fy", 2025:2030),
  tbl_fy_cols = c(paste0("fy_", c(2025:2030)), "fy_total"),
  tbl_fy_labels = c(paste0("FY", c(25:30)), "Total ($K)")
)

report_references <- tar_read(report_references)

cip_project_details <- tar_read(cip_project_details)

agency_reference <- report_references[["agency_reference"]]

report_data <- tar_read(cip_report_data)

cip_recommendations <- tar_read(cip_program_report_stage)
```

```{r}
curr_report_stage_reference <- tar_read(curr_report_stage_reference)

cip_term <- curr_report_stage_reference[["term"]]
cip_singular <- cip_term
cip_plural <- paste0(cip_term, "s")
cip_singular_title <- str_to_title(cip_singular)
cip_plural_title <- str_to_title(cip_plural)
cip_data_col <- paste0(cip_singular, "_data")

cip_verb <- curr_report_stage_reference[["verb"]]
report_org_name <- curr_report_stage_reference[["org_name"]]

# FIXME: See if a long org name should be added to the reference
report_org_name_long <- curr_report_stage_reference[["org_name"]]

report_org_abb <- curr_report_stage_reference[["org_abb"]]

recommendation_date <- format(lubridate::ymd(curr_report_stage_reference[["stage_date"]]), "%B %Y")

stage_filename <- curr_report_stage_reference[["filename"]]
```

```{r}
#| eval: false
sample_n <- 25
report_data <- report_data |>
  slice_sample(n = sample_n)
```

{{< pagebreak >}}

# Introduction

{{< include report/_intro_summary.qmd >}}

{{< include report/_intro_about-cip.qmd >}}

{{< include report/_intro_about-cip-report.qmd >}}

{{< pagebreak >}}

# Capital Project `r cip_plural_title` by Agency

```{r}
#| output: asis
report_data |>
  nest_by(agency_label, .keep = TRUE) |>
  # Create and show each agency report
  knit_children(
    agency_label,
    data,
    .input = here("report", "children", "_agency_report.qmd"),
    .params = list2(
      agency_reference = agency_reference,
      agency_level = 2
    )
  )
```

# Appendices

<!-- {{< include report/_appendix_recommendations.qmd >}} -->

<!-- {{< include report/_appendix_project-identifier.qmd >}} -->

{{< include report/_appendix_report-creation.qmd >}}

{{< include report/_appendix_updates.qmd >}}
