
```{r}
# Custom functions in document
# - gt_revenue_category_fy
# - qto_callout_agency_requests
# - plot_project_locations
# - kbl_agency_projects
# - nest_by_project_code
# - knit_children

request_locations <- project_request_list[["location_data"]] |>
  purrr::list_rbind() |>
  sf::st_as_sf() |>
  dplyr::filter(
    !is.na(asset_id),
    !sf::st_is_empty(geometry)
  )

has_request_locations <- nrow(request_locations) > 0

missing_request_locations <- !has_request_locations

groupname_col <- NULL
group_project_request_tbl <- agency_label %in% c(
  "Department of General Services",
  "Department of Public Works"
)

project_request_tbl_data <- project_request_list

if (group_project_request_tbl) {
  groupname_col <- case_match(
    agency_label,
    "Department of General Services" ~ "asset_agency_label",
    "Department of Public Works" ~ "division"
  )

  project_request_tbl_data <- project_request_list |>
    tidyr::replace_na(
      replace = list(
        division = "No assigned division",
        asset_agency_label = "Multiple Agencies/Other"
      )
    ) |>
    mutate(
      # Required only for DGS asset_agency_label grouping
      asset_agency_label = case_when(
        str_detect(
          project_name,
          "Baltimore City Police Department"
        ) ~ "Baltimore City Police Department",
        # Manual fix for Bromo Seltzer Tower
        project_code == "PRJ003083" ~ "Multiple Agencies/Other",
        .default = asset_agency_label
      )
    )

  project_request_tbl_data <- project_request_tbl_data |>
    group_by(
      .data[[groupname_col]]
    )
}
```

```{r}
quartools::qto_heading(
  paste0("Project ", cip_plural),
  level = agency_level + 1
)
```

```{r}
gt_revenue_category_fy(
  project_request_list[[cip_data_col]],
  title = paste0(
    "Total ",
    agency[["agency_label_abb"]],
    " ", cip_plural, " by source"
  )
)
```


```{r}
#| eval: !expr missing_request_locations
# Show agency callout
qto_callout_agency_requests(
  data = project_request_list,
  agency_label = agency_label,
  callout = FALSE
)
```

::: {layout="[ 60, 40 ]"}
<div>

```{r}
#| eval: !expr has_request_locations
#| layout-valign: top
# Show agency callout
qto_callout_agency_requests(
  data = project_request_list,
  agency_label = agency_label,
  callout = FALSE
)
```

</div>

<div>

```{r}
#| eval: !expr has_request_locations
#| layout-valign: top
#| fig-align: center
#| fig-width: 2
#| fig-height: 2
plot_location_data(
  data = request_locations,
  size = 3
)
```

</div>
:::

```{r}
# Show table of projects with requests
kbl_agency_projects(
  data = project_request_tbl_data,
  groupname_col = groupname_col
)
```

{{< pagebreak >}}

```{r}
#| output: asis
# Walk through agency projects with requests

project_level <- agency_level + 2
internal_report <- FALSE

project_request_list |>
  nest_by_project_code() |>
  knit_children(
    project,
    .input = here("report", "children", "_project_request.qmd"),
    .params = list2(
      "project_level" = project_level,
      "internal_report" = internal_report # ,
      # "cip_location_plots" = cip_location_plots
    )
  )
```
