---
title: "Baltimore City FY25-30 Capital Improvement Program"
author: "Baltimore City Department of Planning"
output-file: "FY2530_CIP-Recommendation-Report_v4.pdf"
date: last-modified
papersize: letter
params:
  cip_type: "recommendation"
  title_short: "FY25-30 CIP Report"
---

```{r}
suppressPackageStartupMessages(
  suppressWarnings(
    targets::tar_source(
      files = here::here("R")
    )
  )
)

cip_singular <- params$cip_type
cip_plural <- paste0(params$cip_type, "s")
cip_singular_title <- str_to_title(cip_singular)
cip_plural_title <- str_to_title(cip_plural)
cip_data_col <- paste0(cip_singular, "_data")

cip_verb <- switch(cip_singular,
  "request" = "requested",
  "recommendation" = "recommended"
)
```

```{r}
store_path <- here(targets::tar_config_get("store"))

# FIXME: Check if all of the following are required or if any can be dropped
report_xwalks <- tar_read(report_xwalks, store = store_path)

cip_requests <- tar_read(cip_requests, store = store_path)

cip_recommendations <- tar_read(cip_recommendations, store = store_path)

cip_comparison_summary <- tar_read(cip_comparison_summary, store = store_path)

cip_project_details <- tar_read(cip_project_details, store = store_path)

asset_list <- tar_read(asset_list, store = store_path)

agency_reference <- tar_read(agency_reference, store = store_path)

report_data <- tar_read(cip_report_data)
```

```{r}
#| eval: false
sample_n <- 10
report_data <- report_data |>
  slice_sample(n = sample_n)
```

{{< pagebreak >}}

# Introduction

{{< include report/_intro_summary.qmd >}}

{{< include report/_intro_about-cip.qmd >}}

{{< include report/_intro_about-cip-report.qmd >}}

{{< pagebreak >}}

# Capital Project `r cip_plural_title` by Agency

```{r}
#| output: asis
report_data |>
  nest_by(agency_label, .keep = TRUE) |>
  # Create and show each agency report
  knit_children(
    agency_label,
    data,
    .input = here("report", "children", "_agency_report.qmd"),
    .params = list2(
      agency_reference = agency_reference,
      agency_level = 2,
      internal_report = FALSE
    )
  )
```

# Appendices

{{< include report/_appendix_recommendations.qmd >}}

{{< include report/_appendix_project-identifier.qmd >}}

{{< include report/_appendix_report-creation.qmd >}}

{{< include report/_appendix_updates.qmd >}}

